sonar.projectKey=vsupruniuk_chatify
sonar.organization=vsupruniuk
sonar.sources=src,.github,scripts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverageReportPaths=coverage/sonar-generic-coverage.xml
sonar.exclusions=dist/**,node_modules/**
sonar.coverage.exclusions=src/main.ts,src/index.html,src/**/*.d.ts,src/configs/**,src/enums/**,src/tests/**,src/types/**,coverage/**
sonar.cpd.exclusions=src/tests/**
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
