sonar.projectKey=vsupruniuk_chatify
sonar.organization=vsupruniuk
sonar.sources=src,.github
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=dist/**,node_modules/**
sonar.coverage.exclusions=src/main.ts,src/index.html,src/**/*.d.ts,src/configs/**,src/enums/**,src/tests/**,src/types/**
sonar.cpd.exclusions=src/tests/**
